obstacle_range: 2.5 #最大障碍物检测范围
raytrace_range: 3.0 #检测自由空间的最大范围
footprint: [[0.31, 0.31], [0.31, -0.31], [-0.31, -0.31], [-0.31, 0.31]] #机器人为矩形，设置矩形的四个点
inflation_radius: 0.5 #膨胀层半径
cost_scaling_factor: 2.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
